export const ADD_CONTENT = "ADD_CONTENT";
export const GET_CONTENT = "GET_CONTENT";
export const UPDATE_CONTENT = "UPDATE_CONTENT";
export const DELETE_CONTENT = "DELETE_CONTENT";
export const READING_HISTORY = "READING_HISTORY";
export const TOGGLE_BRAND = "TOGGLE_BRAND";
export const TOGGLE_STOCK = "TOGGLE_STOCK";